### ISSUE TITLE
By default, mat files are automatically written

### ISSUE THREAD

**Issue by dmlewis9** [edges-collab/read_acq#11]
The default behavior for decode_file() automatically adds writing to .mat, even if write_format = None (the default parameter). Currently can be sidestepped by making write_format = [], but should be fixed to not write if no write format specified.

**Comment by steven-murray** [comment]
I think we can even go one better -- `decode_file` shouldn't do any writing at all. We should have another function (perhaps `convert_file`?) that calls `decode_file` and then does the writing, and its default output should be `h5`.
