### ISSUE TITLE
h5 writer references nonexistent attribute

### ISSUE THREAD

**Issue by dmlewis9** [edges-collab/read_acq#20]
https://github.com/edges-collab/read_acq/blob/fa3edaf36848e8f3cd8819066e0c91f338766520/src/read_acq/writers.py#L56

The method _write_h5() takes in "time_data" as a dict from the ancillary class (inside a dict called "data"). It then tries to loop through the data['time_data'] with a generator expression to create a dict for the time data containing all the original entries and keys. The code currently tries to use data["time_data"].dtype.names to generate these keys, but the attribute '.dtype' is not part of a python dict, and generates an error.

**Comment by steven-murray** [comment]
I believe this is fixed in #18. @dmlewis9 could you review that?

**Comment by steven-murray** [comment]
This should be cleared up now. I will close, but if you experience more trouble, @dmlewis9 , feel free to re-open.
