### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by oopsyrah** [edges-collab/read_acq#68]
I tried to read an acq file recorded and generated on Windows (Japanse environment) using the codes below in Jupiter notebook:

> from read_acq import decode_file
> 
> data = decode_file('path/to/my/file.acq')

=================
error appeard:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 5: ordinal not in range(128)
`

then I tried the same file using another Jupiter notebook,
another error appeared:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 5: invalid start byte
`

**Comment by steven-murray** [comment]
Hi @oopsyrah I think you're probably using the wrong library -- this library is for a very specific data format written by our collaboration for spectrometer data.
