### ISSUE TITLE
powers written as zeros not nans

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/read_acq#7]
At the moment it seems that the ratio is written as nan where data is bad, but the powers (p0, p1 and p2) get written as zero, which can confuse some algorithms (like taking mean/variance).

**Comment by dmlewis9** [comment]
When the power arrays are combined to make the ratio array it occasionally divides by zero, and the runtime errors are suppressed by a surrounding command. This results in a ratio array with a bunch of NaN values; however the power array still has real values

Commit https://github.com/edges-collab/read_acq/commit/94b8616245ae387ee20b355da262be9fdf1c1338 adds a mask for the ratio and power arrays. Values for the power arrays should still be accessible via numpy, but calculations will ignore the masked values.
